CREATE DATABASE QLY_LICHDAY;
USE QLY_LICHDAY;

CREATE TABLE KHOA(
	MAKHOA VARCHAR(10)	PRIMARY KEY,
	TENKHOA NVARCHAR(100)
);

CREATE TABLE LOP(
	MALOP VARCHAR(10) PRIMARY KEY ,
	TENLOP NVARCHAR(100),
	MAKHOA VARCHAR(10),
	FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA)
);

CREATE TABLE SINHVIEN(
	MASV VARCHAR(20) PRIMARY KEY,
	HOTENSV NVARCHAR(50),
	GIOITINH NVARCHAR(10),
	NGAYSINH DATE,
	QUEQUAN NVARCHAR(100),
	MALOP VARCHAR(10), 
	FOREIGN KEY (MALOP) REFERENCES LOP(MALOP)
);

CREATE TABLE MONHOC(
	MAMH VARCHAR(10) PRIMARY KEY,
	TENMH NVARCHAR(50),
	DONVIHT INT
);

CREATE TABLE GIANGVIEN(
	MAGV VARCHAR(10) PRIMARY KEY,
	HOTENGV NVARCHAR(50),
	HOCVI NVARCHAR(50),
	CHUYENNGANH NVARCHAR(20),
	NGAYSINH DATE,
	QUEQUAN NVARCHAR(50),
	GIOITINH VARCHAR(10),
	MAKHOA VARCHAR(10),
	FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA)
);

CREATE TABLE KETQUA(
	MASV VARCHAR(20),
	MAMH VARCHAR(10),
	LANTHI INT,
	DIEMTHI FLOAT,
	PRIMARY KEY ( MASV, MAMH, LANTHI),
	FOREIGN KEY (MASV) REFERENCES SINHVIEN(MASV),
	FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH)
);

CREATE TABLE PHANCONG(
	MALOP VARCHAR(10),
	MAMH VARCHAR(10),
	MAGV VARCHAR(10),
	PRIMARY KEY (MALOP, MAMH, MAGV),
	FOREIGN KEY (MALOP) REFERENCES LOP(MALOP),
	FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH),
	FOREIGN KEY (MAGV) REFERENCES GIANGVIEN(MAGV)
);

DELETE FROM KETQUA
WHERE MASV = 'HuyNVph07543';

UPDATE SINHVIEN
SET QUEQUAN = N'Hà Nội',
	GIOITINH = N'Nam'
WHERE MASV = 'HuyNVph07543';

UPDATE MONHOC
SET	TENMH = N'Cơ sở dữ liệu'
WHERE TENMH = N'Tin Văn Phòng';

UPDATE MONHOC
SET DONVIHT = 30
WHERE TENMH = N'Tri Tue Nhan Tao&quot';

UPDATE SINHVIEN
SET HOTENSV = N'NGUYEN THANH SON',
	GIOITINH = N'NAM'
	WHERE HOTENSV = N'NGUYEN THI LAN';

UPDATE SINHVIEN
SET MALOP = 'Pt14353MoB'
WHERE HOTENSV = N'LE THI LAN ANH';
	

